### PR TITLE
ci: Run affected targets correctly on master and on PR as on 4.x and 1.15x

### PR DESCRIPTION
**Pull request by lukasholzer**
### <strong>Pull Request</strong>

Calculate correct commit hashes so that affected knows always against which target it should compare. Currently, we were always running against master.

- `4.x` against latest commit between the changes and previous commits
- `4.14.x` against latest commit between the changes and previous commits
- `master` against latest commit between the changes and previous commits
- PRs check for the target hash
- commits without PR against origin/master
#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ffriedl89** [comment]
I think this introduces a lot of complexity for the benefits we get, we have enough resources to run the entire pipeline on master, release branches. If we run into problems in the future we can optimize

**Comment by lukasholzer** [comment]
We had the shortages of resources when we had the 4.x and 4.10.x branches and hat to cherry-pick them. 

Currently, we have build times about 10minutes per commit when we need to run all. And we don't run the `build` and `a11y` tests currently on the CI. That means we are using per commit all of the build resources in case we can run max 4 in parallel and we have about 10 jobs that need to be running.

When the release branches are added and we are cherrypicking always commits than those commits have to be built as well alongside the master.

We are trying to create small pull requests – defacto a lot of builds. If we can reduce our CI times and CI waiting times than this is a must in my opinion.

Furthermore, a configuration of the CI is not touched every time in best case it is an initial effort.
Nevertheless compared with the complexity of our old build (Jenkins + Gradle) this is very straight forward.

**Comment by lukasholzer** [comment]
By the way, configuring that only on PRs the affected should be leveraged is quite the same complexity.

**Comment by ffriedl89** [comment]
After talking yesterday, i am fine with the current approach, since it solves a CI bottleneck that we will again experience once we have a 5.x and a 5.0.x branch. Please add troubleshooting the CI information either in this PR or create a followup PR

**Comment by lukasholzer** [comment]
Will add the debugging with ssh https://circleci.com/blog/optimizing-react-native-camera/ to some kind of documentation.

**Comment by tomheller** [comment]
Please also link the referred wiki documentation on how to troubleshoot

**Pull request merged**
