### PR TITLE
feat(tile): Add critical color to tile component

### PR DESCRIPTION
**Pull request by W3D3**
### <strong>Description</strong>

This PR adds support for the critical color theme for the tile component.

image

#### Type of PR

Feature (non-breaking change which adds functionality)

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by ffriedl89 — DISMISSED** [review]

**Review by thomaspink — DISMISSED** [review]
LGTM

**Comment by W3D3** [comment]
CI pipeline doesn't seem to run, could somebody manually (re)start it for this PR?

**Comment by Sherif-Elhefnawy** [comment]
@W3D3 , could you please rebase this on 10.x instead if you need these changes soon?

**Review by Sherif-Elhefnawy — APPROVED** [review]

**Comment by Sherif-Elhefnawy** [comment]
Thank you @W3D3 for the PR, can I bug you to create another PR for master and link to this on here? Just to keep track of things we want included in master as well :)

**Comment by Sherif-Elhefnawy** [comment]
Cherry picked into: 
10.7.x: 31ab3f3fce7c0a8b59273d4d4dcffa44f2cc064d

**Pull request merged**
