### PR TITLE
Fixes SideNav height bug when its content is smaller than view

### PR DESCRIPTION
**Pull request by rowa-audil**
Changes SideNav Height property from 100% to 100vh

### CODE REVIEW

**Comment by lukasholzer** [comment]
Is there an issue connected with this PR?

**Comment by lukasholzer** [comment]
Maybe you can reword your commit to something more descriptive for the changelog:

The scope would be drawer in case you import it from `@dynatrace/barista-components/drawer`

`fix(drawer): Fixes an issue where the side navigation drawer was not expanding to the full-screen height.`

**Comment by rowa-audil** [comment]
Yes: https://github.com/dynatrace-oss/barista/issues/733

**Comment by lukasholzer** [comment]
please add issue number in commit body.

**Pull request merged**
