### PR TITLE
fix(filter-field): Handling asynchronous fetching for multiselect fields.

### PR DESCRIPTION
**Pull request by PedroMosquera**
#### Type of PR

Bugfix (non-breaking change which fixes an issue).

#### In this PR
- Enabling async feature for multiselect fields
- Adding async example in demo
- UX enhancements 
- Adding test for current async implementation

### CODE REVIEW

**Review by tomheller — CHANGES_REQUESTED** [review]
Hi @PedroMosquera ! Thank you for this contribution, the changes look good. 
Would it be possible to add tests as well, which test the async functionality?

**Comment by PedroMosquera** [comment]
> Hi @PedroMosquera ! Thank you for this contribution, the changes look good. 
> Would it be possible to add tests as well, which test the async functionality?
> 
> Additionally I noticed that there are some other tests as well, that are now failing. 
> You should be able to run filter field unit tests with `bazel run //libs/barista-components/filter-field:test`.

Sure @tomheller , I'll do that during the day, thanks!

**Review by tomheller — APPROVED** [review]

**Comment by tomheller** [comment]
Thanks for taking care of the tests. Changes and checks look good now.

**Review by ffriedl89 — APPROVED** [review]

**Comment by tomheller** [comment]
cherry picked manually to 9.x and 9.0.x

**Pull request merged**
