### PR TITLE
Feat/sunburst chart mobile friendly

### PR DESCRIPTION
**Pull request by PedroMosquera**
#### Type of PR

Bugfix (non-breaking change which fixes an issue)

Changing sunburst-chart's width in order to support small screens (e.g. mobile phones)

**Before**
image

**After**
image

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by tomheller** [comment]
Could you please run `yarn nx format:write` to apply the formatting rules? 

This should be run as a precommit hook. Could you elaborate how you added your commit (UI, cli, operating system), for us to iron out potential problems.

**Comment by PedroMosquera** [comment]
Hi @tomheller,

I did, the lasts commits, it using **Ubuntu's Terminal**.

I usually work with:
- MacOS Catalina (Now Big Sur)
- iTerm as CLI
- VS Code as Editor

Sometimes I use git functionalities within VS Code for commiting and pushing, if that helps.

**Comment by tomheller** [comment]
Thank you @PedroMosquera! This helps I'll continue to have an eye on why the formatter is not working in some cases. Thank you for fixing the issue

**Review by rowa-audil — DISMISSED** [review]
LGTM

**Comment by tomheller** [comment]
Looks good, please rebase and squash your commits to a single `feat` commit.

**Comment by tomheller** [comment]
Looks good now, thanks @PedroMosquera! @subarroca do you want to take another look?

**Review by subarroca — APPROVED** [review]

**Pull request merged**
