### PR TITLE
feat(chart-range): Add possibility to close chart-range programmatically.

### PR DESCRIPTION
**Pull request by dovidio**
### <strong>Pull Request</strong>
Added close method to the `DtChartRange`

#### Type of PR
Feature (non-breaking change which adds functionality)

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by thomaspink** [comment]
We are currently changing some CI stuff, thats why some checks are maybe failing. We will post you when the CI is up and running again and some changes have to be made.

**Comment by tomheller** [comment]
Thank you for your contribution @dovidio. Changes look good to me 👍

**Comment by ffriedl89** [comment]
Thank you @dovidio for the contribution! I think it would make sense to add the same function to the dt-chart-timestamp component as well? @dovidio would you be willing to add this here as well or should we create a followup issue?

**Comment by lukasholzer** [comment]
Please rebase the master in your PR, so that the CI checks are passing.

**Comment by dovidio** [comment]
Good point @ffriedl89! I omitted that because we don't need it for our case, but I think it would make sense to add it. I would personally add another issue for this if it's fine with you

**Comment by ffriedl89** [comment]
@dovidio we had some issues with the ci workflow, could you please rebase our current master onto your branch and force push?

**Pull request merged**
