### PR TITLE
fix(key-value-list): Change CSS to fix overflow issues fixes #690

### LINKED ISSUE #690: [dt-key-value-list] Expanding selection - text displacement
# Bug Report

## Expected Behavior
When text is selected from key-value list component, with "shift+arrow" text selection will be expanded / shrinked.

## Current Behavior
It expands selection, but it also moves selected text in key-value pair.

## Steps to Reproduce
Example code: https://stackblitz.com/edit/github-bd8pek
1. Select value in last key-value pair in first KV list
2. With "shift+ right arrow" expand selection
3. When it will go out of the KV list some weird thing will happen with selected key-value pair.

Bug exists in Chrome. My version is 80.0.3987.122 (Official Build) (64-bit). I've checked it in Firefox and there it works fine. I'm using Windows 10.

### Used Versions:
- **node**: 12.12.6
- **npm**: 4.1.5
- **typescript**: 3.7.5
- **angular**: 9.0.4
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 5.2.0

## Attachments
example

### PR DESCRIPTION
**Pull request by ddprrt**
#### Type of PR

Bugfix (non-breaking change which fixes an issue) 
#### Checklist

- [X] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [X] Lint and unit tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ddprrt** [comment]
CC @tomheller

**Comment by tomheller** [comment]
**Chrome selection behavior has also been fixed with one.** 
key-value-list-selection

## Tested the refactoring of the styles in

**Safari**
Safari Key value list

**Firefox**
Safari Key value list

**Edge 18**
Edge 18 key value list

**Chrome**
Chrome key value list

**Comment by tomheller** [comment]
Amazing fix @ddprrt, thank you for being such a css-magician 🙇

**Comment by ddprrt** [comment]
I'm happy because now I actually earned my chocolate :D :D

**Comment by tomheller** [comment]
Manually cherry picked to `6.x` and `6.0.x`...

**Pull request merged**
