### PR TITLE
feat(filter-field): Add disable state to the option without group

### PR DESCRIPTION
**Pull request by RuzzleDuzzle**
### <strong>Pull Request</strong>

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tomheller** [comment]
Hi @RuzzleDuzzle!
Thank you for your contribution. Could you elaborate why this is needed. Does it make sense to present disabled options in the filter field over _not displaying_ it in general?

**Comment by RuzzleDuzzle** [comment]
Hi @tomheller !
The contribution was done for two reasons: in case if we want to show user text input as a disabled suggestion we don't need a group (as it has name property which is excessive in that case) + to keep consistency in options' behaviour  (if user can disable group options, he will assume that he can disable simple options as well)

**Comment by ffriedl89** [comment]
@RuzzleDuzzle Thx for the contribution, could you please provide an example for this setting being applied. I want to check it out in the browser myself to check about the impact. Please also provide a test case that covers that functionality.

**Comment by RuzzleDuzzle** [comment]
@ffriedl89 I've updated the demo with disabled option and added unit test  👍🏻

**Review by thomaspink — APPROVED** [review]

**Comment by thomaspink** [comment]
LGTM

**Review by tomheller — APPROVED** [review]

**Comment by tomheller** [comment]
Manually cherry picked to 9.x, new head d25f2adce2a2d0523f55f4dde6a9371145f7b0df

**Pull request merged**
