### PR TITLE
build(barista-tools): Build Barista Tools with Bazel

### LINKED ISSUE #1135: Bazel: Build barista tools with bazel
# Feature Request

For the server-side rendering, the content for barista from strapi is needed therefore we have to build the barista tools with bazel.

To run a the output we can utilize the `npm_package_bin` this creates an output that would be normally generated via the `bazel run binary`

```python

nodejs_binary(
    name = "barista_tools_binary",
    data = [":compile"],
    entry_point = "src/main.ts",
)

npm_package_bin(
    name = "barista-tools",
    tool = ":barista_tools_binary,
    outs = ["...generated files"],
    data = [

    ],
)

```

### PR DESCRIPTION
**Pull request by SkaillZ**
### <strong>Pull Request</strong>

Closes #1135.

#### Type of PR

Other

### CODE REVIEW

**Review by lukasholzer — DISMISSED** [review]
Awesome thank you very much for getting us one step closer to build barista with bazel! :)

**Comment by lukasholzer** [comment]
@ffriedl89 why is the cla bot not responding? Any known issues?

**Comment by ffriedl89** [comment]
@lukasholzer No not that I am aware of. @danielkhan Do you know of any issues with the cla bot?

**Comment by SkaillZ** [comment]
Seems like force-pushing fixed it.

**Review by lukasholzer — DISMISSED** [review]

**Comment by lukasholzer** [comment]
Please test the changes from #1782 and rebase them into that we don't leak internal links

**Review by lukasholzer — APPROVED** [review]

**Comment by lukasholzer** [comment]
@SkaillZ have you tested this? https://github.com/dynatrace-oss/barista/pull/1769#issuecomment-720952814

**Comment by SkaillZ** [comment]
> @SkaillZ have you tested this? [#1769 (comment)](https://github.com/dynatrace-oss/barista/pull/1769#issuecomment-720952814)

Yes, seems to work.

**Review by tomheller — APPROVED** [review]

**Review by lukasholzer — APPROVED** [review]

**Pull request merged**
