### PR TITLE
fix(chart): Fix dynamic heatfield generation that was not possible.

### LINKED ISSUE #1580: Incorrect displaying of highchart heatfield
# Bug Report

## Expected Behavior

Heatfields over chart should be displayed according to their start and end attributes and with related overlays.

## Current Behavior

Only one heatfield is displayed without meaningful overlay.

## Steps to Reproduce

https://stackblitz.com/edit/github-4q9fhd?file=src/chart/chart-heatfield-example/chart-heatfield-example.ts

## Context (Environment)

We've got list of problems/events with start and end time and want to display them as heatfields using the Angular's *ngFor directive.

### Used Versions:

- **node**: 12.18.1
- **npm**: 6.14.5
- **typescript**: 3.9.7
- **angular**: 10.0.9
- **@angular/cdk**: 10.1.1
- **@dynatrace/barista-components**: 8.0.0

## Detailed Description

There is an error in Barista highchart heatfield implementation when change is involved. One heatfield is displayed at at full width and even extending chart's range.

The problem occurs when heatfields element are added by Angular's *ngFor directive which iterates over a collection of time ranges and there is a change collection to display. As you can see in the attached example, changing to other list (reference) with the same values is sufficient to encounter the bug.

In the devtools I noticed that position of heatfields is managed by inline style left and width parameters. When this bug occurs style elements are not applied at all, looks like some race condition.

### PR DESCRIPTION
**Pull request by lukasholzer**
Fixes an issue where the heatfields could not be created dynamic.

Fixes #1580

### <strong>Pull Request</strong>

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Checklist

- [ ] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by rowa-audil — COMMENTED** [review]
bazel-unit-tests are failing

Otherwise LGTM

**Review by bardosmisi — APPROVED** [review]

**Review by peter-affenzeller — DISMISSED** [review]

**Review by bardosmisi — DISMISSED** [review]

**Review by rowa-audil — CHANGES_REQUESTED** [review]

**Review by peter-affenzeller — APPROVED** [review]
what he said 😄  else 👍

**Comment by rowa-audil** [comment]
@lukasholzer I let the a11y tests run again to see if there are different tests failing.
Previously the alert and chart-heatfield checks failed

**Comment by lukasholzer** [comment]
> @lukasholzer I let the a11y tests run again to see if there are different tests failing.
> Previously the alert and chart-heatfield checks failed

I'm currently on fixing them that is a different error that is related to my changes somehow.

**Review by bardosmisi — APPROVED** [review]
Interesting hack with zone.js. 🐨

**Review by rowa-audil — APPROVED** [review]

**Pull request merged**
