### PR TITLE
ds: Use installed instead of checked-out icons as icon-page source

### LINKED ISSUE #1404: [Barista tools]: Replace the generation of icon pages source
Currently we rely on the barista-icons sources being checked out to generate the icon pages.
https://github.com/dynatrace-oss/barista/blob/master/libs/tools/barista/src/builder/icons.ts

To simplify this and unify the sourcing of files between barista.dynatrace.com/resources/icons and barista.dynatrace.com/components/icon we should move the generation of the files to source the installed data from @dynatrace/barista-icons npm package.

### PR DESCRIPTION
**Pull request by tomheller**
### <strong>Pull Request</strong>

Fixes #1404

#### Type of PR

Other

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by lukasholzer** [comment]
We need the checked out icons for generating the icon page I thought? That was the reason why we could not use the one from the node_modules

**Comment by tomheller** [comment]
> We need the checked out icons for generating the icon page as we need the matching json file.
That was the reason why we could not use the one from the node_modules – the jsons are only in the repo source folder.

You are correct, but the circumstances have changed. And considering that the json files are now part of the published package since #1403 is resolved, we no longer need to checkout the repo source.

**Comment by lukasholzer** [comment]
> > We need the checked out icons for generating the icon page as we need the matching json file.
> > That was the reason why we could not use the one from the node_modules – the jsons are only in the repo source folder.
> 
> You are correct, but the circumstances have changed. And considering that the json files are now part of the published package since #1403 is resolved, we no longer need to checkout the repo source.

Nice! That simplifies the situation :) Cool that it is possible now 👍  Have you checked the internal build (Jenkins) with this branch?

**Comment by tomheller** [comment]
> Have you checked the internal build (Jenkins) with this branch?

Not yet, but it should be fine as we already source node_modules icons for the icon demo page under the components root page. 

I will start a test-run on jenkins for that branch a little later.

**Comment by tomheller** [comment]
I tried a test run and it failed with the following: 
```
09:35:31  [Error: EISDIR: illegal operation on a directory, read] {
09:35:31    errno: -21,
09:35:31    code: 'EISDIR',
09:35:31    syscall: 'read'
09:35:31  }
```

Probably this is because the node_modules are somehow symlinked. This seems to be more tricky than expected.

**Comment by lukasholzer** [comment]
> I tried a test run and it failed with the following:
> 
> ```
> 09:35:31  [Error: EISDIR: illegal operation on a directory, read] {
> 09:35:31    errno: -21,
> 09:35:31    code: 'EISDIR',
> 09:35:31    syscall: 'read'
> 09:35:31  }
> ```
> 
> Probably this is because the node_modules are somehow symlinked. This seems to be more tricky than expected.

there is the https://nodejs.org/api/cli.html#cli_preserve_symlinks `--preserve-symlinks` flag in nodejs maybe you have to add it to the node script.

**Comment by lukasholzer** [comment]
Pipeline successfully passed and all the icons are the same 

image

**Review by SkaillZ — APPROVED** [review]

**Review by heartdisease — APPROVED** [review]

**Pull request merged**
