### PR TITLE
Fixes an issue that was introduced through rebase strategy

### PR DESCRIPTION
**Pull request by lukasholzer**
The theming file was deleted but due to the rebase strategy it broke the build now.

### <strong>Pull Request</strong>

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Checklist

- [ ] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tomheller** [comment]
If you think it will help us in the long run, please enable the `branches need to be up-do-date` check again.

**Comment by lukasholzer** [comment]
> If you think it will help us in the long run, please enable the `branches need to be up-do-date` check again.

As you mentioned it is a trade of in case of re-requesting reviews because of dismissed reviews I mean we can leverage a pragmatic approach that if it is already marked as merge ready and it needs a rebase without code change and the checks are passing we continue and merge it with admin rights?
@ffriedl89 what do you think?

**Comment by tomheller** [comment]
@lukasholzer as you requested last time, there was a change made in the labeler, that removes the merge ready label, if there are no accepted reviews present. In this case, event the admin rights would not help you. Only if you really want to do the cherry-picking yourself.

**Comment by lukasholzer** [comment]
on your pull request (the keyboard lib) the labeler did not remove any labels.

**Pull request merged**
