### PR TITLE
build: Remove token generation step and outdated dependencies.

### PR DESCRIPTION
**Pull request by tomheller**
### <strong>Pull Request</strong>

- Fixes outdated dependency to highlight.js 9 -> handlebars helpers -> theo
- Removes only the generation of tokens, output is still there to be able to build depending apps.

#### Type of PR

Other

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by lukasholzer — APPROVED** [review]
wow, big chunk of deletions.

**Comment by tomheller** [comment]
> wow, big chunk of deletions.

Token generation has been deleted. This comes with a lot of code that is no longer needed and a couple of dependencies, that could be removed. Hence the large deletion chunk.

**Review by rowa-audil — APPROVED** [review]

**Review by lukasholzer — APPROVED** [review]

**Comment by tomheller** [comment]
Rebased to resolve conflicts

**Review by rowa-audil — APPROVED** [review]
LGTM (since you only rebased I didn't review again)

**Pull request merged**
