### PR TITLE
chore: Use official leonardo package

### PR DESCRIPTION
**Pull request by tomheller**
### <strong>Pull Request</strong>
Switch to official leonardo package after they have resolved their issues with module imports in node 12. 

#### Type of PR
Other

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tomheller** [comment]
>Should the file './contrast-colors'; be removed then as well? 

Yes, sorry I missed that one.

**Comment by tomheller** [comment]
Rebased due to conflicts...

**Comment by lukasholzer** [comment]
> Rebased due to conflicts...

Still conflicts

**Comment by tomheller** [comment]
> > Rebased due to conflicts...
> 
> Still conflicts

SIGH

**Comment by tomheller** [comment]
Fixed conflicts again! this time for real :D

**Pull request merged**
