### PR TITLE
refactor(expandable-section): Switch to custom properties for theming.

### PR DESCRIPTION
**Pull request by nimrod13**
### <strong>Pull Request</strong>

<hr>
As part of the "Switch to custom properties for theming" issue, this changes the theming to custom properties for the expandable-section.

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by lukasholzer — APPROVED** [review]
Awesome! 🐈

**Review by rowa-audil — APPROVED** [review]
LGTM

**Review by tomheller — APPROVED** [review]
Great work 🎉 🐠

**Comment by nimrod13** [comment]
Thanks! :)

**Pull request merged**
