### PR TITLE
feat(chart): Added series heatmaps options to dt chart series type

### PR DESCRIPTION
**Pull request by RuzzleDuzzle**
### <strong>Pull Request</strong>

Due to Heatmaps chart in development the DtChartSeries type should be extended with SeriesHeatmapOptions.

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ffriedl89** [comment]
Hey @RuzzleDuzzle could you please provide an example using a heatmap in the libs/examples directory so that we can add it to barista as well :) ? It would be highly appreciated!

**Review by ffriedl89 — APPROVED** [review]

**Comment by RuzzleDuzzle** [comment]
@ffriedl89 As Lukas Holzer doesn't work on barista anymore, is it possible to merge the PR without his approval?

**Comment by ffriedl89** [comment]
Yes we can, we have a caretaker rotation that takes care of merging and cherry-picking PRs from forks. 
@nimrod13 Could you take care of it please :)

**Comment by tomheller** [comment]
Manually cherry picked to 9.x, new head 8b95369993345fed442eac1bc407d4b975191b00

**Comment by nimrod13** [comment]
> Yes we can, we have a caretaker rotation that takes care of merging and cherry-picking PRs from forks.
> @nimrod13 Could you take care of it please :)

@ffriedl89, sorry, saw this too late. Thanks, @tomheller

**Pull request merged**
