### PR TITLE
feat(colors): add FLAT_WHITE to colors enum

### PR DESCRIPTION
**Pull request by ddprrt**
Dynatrace Barista shouldn't be the only Barista that can't serve a Flat White.

#### FEATURE

A Barista has to be able to serve a Flat White

#### Checklist

- [X] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [X] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by lukasholzer** [comment]
Please provide a feature proposal why we need that. 😂

**Comment by ddprrt** [comment]
Can I haz chocolate now

**Comment by tomheller** [comment]
Please do not merge this one before 6.0.0 is released, cherry picker might do weird stuff.

**Comment by tomheller** [comment]
Please rebase from master to resolve the conflicts. 

I think we can merge this one, but do not  add `merge ready` or `target` labels on there, as this would confuse the cherry picker.

**Pull request closed without merging**
