### PR TITLE
fix(stacked-series-chart): Clear selection working on stack mode

### PR DESCRIPTION
**Pull request by dani7cl**
**In this PR**
[APM-282124] Clearing selection from the outside was not working on the new stack mode. Issue fixed, unit tests and a button to check it on dev environment added

There are 3 commits, but one is from the related PR https://github.com/dynatrace-oss/barista/pull/1958 and the other one is the merge to solve conflicts

### CODE REVIEW

**Review by subarroca — DISMISSED** [review]

**Comment by nimrod13** [comment]
Hey @dani7cl! Thank you for the fix! Could you please squash your commits into one?

**Comment by dani7cl** [comment]
> Hey @dani7cl! Thank you for the fix! Could you please squash the commits?

I had issues with the interactive rebasing because I created this PR from another branch which was pending to be reviewed. Now I've tried again, managed to squash them but then conflicts appeared again and solved them from github which created another merge commit, hope it is fine because now there are many commits from master in between...

**Comment by ffriedl89** [comment]
I think that something went wrong here @dani7cl - can we close this PR? The only change is in a demo.

**Comment by dani7cl** [comment]
> I think that something went wrong here @dani7cl - can we close this PR? The only change is in a demo.

Changes were lost rebasing, I guess it's easier creating a new PR, here it is https://github.com/dynatrace-oss/barista/pull/1992. You can close this one

**Pull request closed without merging**
